import { createHash } from 'node:crypto';
import { interpretDocument } from './document-interpreter.mjs';
export async function documentCycle(worker,interpret=interpretDocument){
 const api=async(route,body={})=>{const r=await worker.request(worker.origin+'/api/finance-documents/worker/'+route,{method:'POST',headers:{Authorization:'Bearer '+worker.config.token,'Content-Type':'application/json'},body:JSON.stringify(body),redirect:'error',signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('Document API '+r.status);return r.json()};
 const {job}=await api('claim');if(!job)return false;let heartbeating=false;const timer=setInterval(async()=>{if(heartbeating)return;heartbeating=true;try{await worker.api('heartbeat')}catch{}finally{heartbeating=false}},20000);
 try{let result;try{if(!/^[a-f\d]{24}$/.test(job.id)||!Number.isInteger(job.size)||job.size<1||job.size>10*1024*1024)throw Error('Invalid document job');const r=await worker.request(worker.origin+'/api/finance-documents/worker/'+job.id+'/file?lease='+encodeURIComponent(job.lease),{headers:{Authorization:'Bearer '+worker.config.token},redirect:'error',signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('Document download failed');const reader=r.body.getReader(),chunks=[];let total=0;for(;;){const {done,value}=await reader.read();if(done)break;total+=value.byteLength;if(total>job.size){await reader.cancel();throw Error('Document exceeds expected size')}chunks.push(Buffer.from(value))}const bytes=Buffer.concat(chunks);if(bytes.length!==job.size||createHash('sha256').update(bytes).digest('hex')!==job.hash)throw Error('Document hash mismatch');result=await interpret(worker.config,job,bytes);}catch{await api(job.id+'/result',{lease:job.lease,hash:job.hash,failed:true});worker.log('Document extraction needs retry');return true}
 await api(job.id+'/result',{lease:job.lease,hash:job.hash,result:{complete:result.complete,pages:result.pages,records:result.records.map(r=>({fields:r.fields.map(f=>({...f,value:String(f.value)}))}))}});worker.log('Document evidence prepared');return true;
 }finally{clearInterval(timer)}
}
