<template>
  <section v-if="busy || error || groups.length || message" class="card mb-6 p-4 sm:p-6" data-customer-mapping-review>
    <div class="flex flex-wrap items-start justify-between gap-3"><div><h2 class="text-base font-semibold text-gray-900 dark:text-gray-100">顧客の商品代金をショップごとに確認</h2><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">勘定科目が空欄の {{ total }}件 · {{ groups.length }}グループ</p></div><button type="button" class="btn btn-secondary text-xs" :disabled="busy" @click="load">候補を更新</button></div>
    <p v-if="error" role="alert" class="mt-3 break-words text-sm text-red-600">{{ error }}</p><p v-if="message" role="status" class="mt-3 text-sm text-green-700 dark:text-green-400">{{ message }}</p><p v-if="busy && !groups.length" role="status" class="mt-3 text-sm text-gray-500">商品代金の分類を確認しています…</p>
    <p v-if="truncated" class="mt-3 text-xs text-amber-700">先頭160件の支出から表示しています。取込明細を絞ると残りも確認できます。</p>
    <template v-if="group">
      <p class="mt-3 text-sm leading-relaxed text-gray-600 dark:text-gray-300">同じ顧客・カード・利用先の明細をまとめました。表示された顧客の商品代金かを確認し、販売か立替かを選びます。内容が異なる明細は選択から外してください。</p>
      <label class="mt-4 block text-xs text-gray-500" for="customer-review-group">確認するショップ</label><select id="customer-review-group" v-model="activeId" class="mt-2 w-full min-w-0 rounded-lg border border-gray-300 bg-white px-3 py-2.5 text-sm text-gray-900 focus:border-primary-main focus:outline-none focus:ring-1 focus:ring-primary-main dark:border-white/10 dark:bg-gray-800 dark:text-gray-100" :disabled="busy"><option v-for="g in groups" :key="g.id" :value="g.id">{{ g.merchant }} · {{ g.card }} · {{ g.customerName }} · {{ g.rows.length }}件</option></select>
      <div class="mt-4 rounded-xl bg-gray-50 p-4 dark:bg-white/5"><h3 class="break-words text-sm font-semibold text-gray-900 dark:text-gray-100">{{ group.merchant }}</h3><p class="mt-1 break-words text-xs text-gray-500">{{ group.customerName }} · {{ group.card }} · 区分：{{ group.category }}</p><p class="mt-2 text-sm tabular-nums">{{ group.rows.length }}件 / {{ yen(group.rows.reduce((sum:number,r:any)=>sum+r.amount,0)) }}</p>
      <details class="mt-3 text-xs leading-relaxed text-gray-500"><summary class="cursor-pointer py-1 text-primary-main">顧客・区分の根拠と購入方法</summary><p class="mt-2">{{ group.mappingReason }}</p><p v-if="group.originalCategory" class="mt-2">元シートの区分：{{ group.originalCategory }}</p><template v-for="context in group.workflow" :key="context.id"><p class="mt-3 font-medium">確認済みの購入方法</p><p v-for="route in context.routes" :key="route.key" class="mt-1">{{ route.label }}</p><p class="mt-2">{{ context.scope }}</p></template><p class="mt-2">カードやショップのアカウント名だけでは、販売・立替の処理を決めません。</p></details></div>
      <div class="mt-4 flex flex-wrap gap-3 text-xs"><button type="button" class="py-2 text-primary-main" data-select-customer-group :disabled="busy" @click="selected=group.rows.slice(0,30).map(identity);confirmed=false">{{ group.rows.length>30?'先頭30件':'このグループ' }}を選択</button><button type="button" class="py-2 text-gray-500" :disabled="busy" @click="selected=[];confirmed=false">選択を解除</button><span class="py-2 text-gray-500">{{ selected.length }}件選択</span></div>
      <div class="max-h-72 overflow-y-auto divide-y divide-gray-200 border-y border-gray-200 dark:divide-white/10 dark:border-white/10"><article v-for="row in group.rows" :key="identity(row)" class="flex items-start gap-3 py-3" :data-customer-line="row.line"><input v-model="selected" type="checkbox" :value="identity(row)" :aria-label="row.date+' '+yen(row.amount)+'を選択'" :disabled="busy || selected.length>=30&&!selected.includes(identity(row))" class="mt-1 rounded border-gray-300 text-primary-main" @change="confirmed=false"><div class="min-w-0 flex-1"><div class="flex flex-wrap justify-between gap-2 text-sm"><span>{{ row.date }}</span><span class="tabular-nums">{{ yen(row.amount) }}</span></div><NuxtLink :to="'/mapping-draft/'+row.importId+'/'+row.line" class="inline-block py-2 text-xs text-primary-main">明細・根拠を個別に確認 →</NuxtLink></div></article></div>
      <fieldset class="mt-4" :disabled="busy"><legend class="text-sm font-medium text-gray-900 dark:text-gray-100">この商品代金は、どの取引ですか？</legend><div class="mt-3 grid gap-3 sm:grid-cols-2"><label v-for="t in treatments" :key="t.id" class="flex items-start gap-3 rounded-xl border p-4 text-sm" :class="treatment===t.id?'border-primary-main bg-primary-main/5':'border-gray-200 dark:border-white/10'"><input v-model="treatment" type="radio" name="customer-treatment" :value="t.id" :disabled="!available(t.id)" class="mt-1 text-primary-main" :data-customer-treatment="t.id"><span class="min-w-0"><strong class="block font-medium">{{ t.label }}</strong><span class="mt-2 block text-xs leading-relaxed text-gray-500">{{ t.confirmation }}</span><span class="mt-2 block text-xs font-medium">空欄 → {{ t.account }}</span><span v-if="!available(t.id)" class="mt-2 block text-xs text-amber-700">{{ t.account }}の登録・重複を個別に確認してください。</span></span></label></div></fieldset>
      <div v-if="chosen" class="mt-4 rounded-xl bg-gray-50 p-4 dark:bg-white/5"><label class="flex items-start gap-3 text-sm leading-relaxed"><input v-model="confirmed" type="checkbox" data-confirm-customer-goods :disabled="busy || !selected.length" class="mt-1 rounded border-gray-300 text-primary-main"><span>{{ chosen.confirmation }}</span></label><p class="mt-3 text-xs text-gray-500">購入品・顧客・取引内容が一致する選択明細だけに適用します。</p><a :href="chosen.source.url" target="_blank" rel="noopener noreferrer" class="mt-2 inline-block py-2 text-xs text-primary-main underline">{{ chosen.source.title }}</a></div>
      <button type="button" class="btn btn-primary mt-4 text-sm" data-save-customer-goods :disabled="busy || !selected.length || !chosen || !confirmed || !available(treatment)" @click="save">{{ selected.length }}件の勘定科目を下書きに保存</button><p class="mt-3 text-xs leading-relaxed text-gray-500">判断がつかない明細は個別に確認できます。税区分・税率・インボイスの確認と帳簿への登録は、下書きで続けます。</p>
    </template>
  </section>
</template>
<script setup lang="ts">
import {useUserStore} from '~/stores/user'
const props=defineProps<{importIds:string[]}>(),emit=defineEmits<{saved:[]}>(),user=useUserStore(),groups=ref<any[]>([]),treatments=ref<any[]>([]),activeId=ref(''),selected=ref<string[]>([]),treatment=ref(''),confirmed=ref(false),busy=ref(false),error=ref(''),message=ref(''),truncated=ref(false)
const group=computed(()=>groups.value.find(g=>g.id===activeId.value)),chosen=computed(()=>treatments.value.find(t=>t.id===treatment.value)),total=computed(()=>groups.value.reduce((sum,g)=>sum+g.rows.length,0)),identity=(r:any)=>r.importId+':'+r.line,yen=(n:number)=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY'}).format(n)
function available(id:string){return !!group.value?.rows.length&&group.value.rows.filter((r:any)=>!selected.value.length||selected.value.includes(identity(r))).every((r:any)=>r.choices.some((c:any)=>c.treatment===id))}
let generation=0
async function load(){const run=++generation;busy.value=true;error.value='';selected.value=[];treatment.value='';confirmed.value=false;try{const response:any=await $fetch('/api/finance-customer-review',{headers:user.authHeader,query:{imports:props.importIds.join(',')}});if(run!==generation)return;groups.value=response.groups;treatments.value=response.treatments;truncated.value=response.truncated;if(!groups.value.some(g=>g.id===activeId.value))activeId.value=groups.value[0]?.id||''}catch(e:any){if(run===generation){groups.value=[];error.value=e.data?.data?.message||e.data?.statusMessage||'候補を読み込めませんでした。'}}finally{if(run===generation)busy.value=false}}
async function save(){if(busy.value||!confirmed.value||!chosen.value||!selected.value.length||!available(treatment.value))return;const run=generation;busy.value=true;error.value='';message.value='';const choices=group.value.rows.filter((r:any)=>selected.value.includes(identity(r))).map((r:any)=>({importId:r.importId,line:r.line,treatment:treatment.value,key:r.choices.find((c:any)=>c.treatment===treatment.value).key}));try{const result:any=await $fetch('/api/finance-customer-review',{method:'POST',headers:user.authHeader,body:{rows:choices,confirmGoods:true}});if(run!==generation)return;message.value=(result.saved+result.alreadySaved)+'件の勘定科目を下書きに保存しました。'+(result.failed?result.failed+'件は再確認が必要です。':'');await load();if(result.failed)error.value=result.results.filter((r:any)=>r.state==='failed').map((r:any)=>'明細 '+r.line+': '+r.message).join(' ');emit('saved')}catch(e:any){if(run===generation)error.value=e.data?.data?.message||e.data?.statusMessage||'保存結果を確認できませんでした。同じ選択で再試行できます。'}finally{if(run===generation)busy.value=false}}
watch(activeId,()=>{selected.value=[];treatment.value='';confirmed.value=false});watch(treatment,()=>{confirmed.value=false});watch(()=>props.importIds.join(','),()=>{message.value='';load()},{immediate:true});onBeforeUnmount(()=>{generation++})
</script>
