<template>
 <section class="mt-5 border-t border-gray-100 pt-4 dark:border-white/10" data-purchase-exports aria-label="購入から輸出まで">
  <div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="text-sm font-semibold">購入から輸出まで</h3><p v-if="data" class="mt-1 text-xs" data-export-progress :class="data.progress.state==='complete'?'text-green-700 dark:text-green-400':'text-gray-600 dark:text-gray-300'">{{ statusLabel(data.progress.state) }} · 輸出証憑 {{ data.progress.exported }} / {{ data.progress.total }}点<span v-if="data.progress.resolved"> · 返品・取消 {{ data.progress.resolved }}点</span></p></div><button type="button" class="text-xs text-primary-main underline" :disabled="busy || disabled" @click="form=null;outcomeForm=null;load()">再読込</button></div>
  <p class="mt-2 text-xs leading-relaxed text-gray-500">保存済みの購入について、在庫ごとに出荷と書類を確認します。会計の確認・帳簿への登録は別に管理します。</p>
  <p v-if="data&&!data.progress.evidenceComplete" class="mt-2 text-xs text-amber-700">購入原本または支払いとの一致を確認できません。購入から輸出までの完了には数えません。</p>
  <p v-if="error" role="alert" class="mt-3 text-xs text-red-600">{{ error }}</p><p v-if="message" role="status" class="mt-3 text-xs text-green-700">{{ message }}</p>
  <template v-if="data">
   <div class="mt-3 space-y-2"><div v-for="unit in data.progress.units" :key="unit.inventoryId" class="flex flex-wrap justify-between gap-2 rounded-lg bg-gray-50 p-3 text-xs dark:bg-white/5"><span class="break-all font-medium">{{ unit.inventoryId }}</span><span :class="unit.state==='exported'?'text-green-700 dark:text-green-400':'text-gray-500'">{{ unitLabel(unit.state) }}<span v-if="unit.exportId"> · {{ data.exports.find((e:any)=>e.id===unit.exportId)?.orderId }}</span></span></div></div>
   <p v-if="data.progress.units.length < data.progress.total" class="mt-2 text-xs text-amber-700">{{ data.progress.total-data.progress.units.length }}点は在庫の接続待ちです。</p>
   <article v-for="record in data.exports" :key="record.id" class="mt-3 rounded-lg border border-gray-200 p-3 text-xs dark:border-white/10" data-export-record>
    <div class="flex flex-wrap justify-between gap-2"><p class="font-medium">{{ record.orderId }} · {{ record.tracking }}</p><span :class="record.documentsComplete?'text-green-700':'text-amber-700'">{{ record.documentsComplete?'Invoice・許可書 確認済み':'書類の確認待ち' }}</span></div>
    <p class="mt-2 text-gray-500">出荷 {{ record.shippedAt }} · 割当 {{ record.allocations.length }} / {{ record.itemCount }}点 · お客様の申告額 {{ yen(record.declaredValue.amount) }}</p>
    <p v-if="record.permitNumber" class="mt-1 text-gray-500">輸出許可 {{ record.permitDate }} · {{ record.permitNumber }}</p>
    <p v-if="record.documentIntegrity===false" class="mt-2 text-amber-700">保管資料の整合性を確認できません。原本を確認してください。</p>
    <div class="mt-3 flex flex-wrap gap-3"><button v-for="doc in record.documents" :key="doc.kind" type="button" class="text-primary-main underline" :disabled="busy" @click="download(record,doc)">{{ doc.kind==='invoice'?'Invoice PDF':'輸出許可書 PDF' }}</button><button type="button" class="text-primary-main underline" :disabled="busy||disabled" @click="edit(record)">出荷を確認・更新</button><button type="button" class="text-gray-500 underline" :disabled="busy||disabled" @click="release(record)">割当を解除</button></div>
   </article>
   <article v-for="outcome in data.outcomes" :key="outcome.id" class="mt-3 rounded-lg border border-gray-200 p-3 text-xs dark:border-white/10"><p class="font-medium">{{ outcome.inventoryId }} · {{ outcome.outcome==='returned'?'返品':'取消' }}確認済み</p><p class="mt-1 whitespace-pre-wrap text-gray-500">{{ outcome.reason }}</p><div class="mt-2 flex gap-3"><button type="button" class="text-primary-main underline" :disabled="busy" @click="download(outcome,outcome.documents[0],true)">確認資料</button><button type="button" class="text-gray-500 underline" :disabled="busy||disabled" @click="releaseOutcome(outcome)">解除</button></div></article>
   <div class="mt-4 flex flex-wrap gap-3"><button type="button" class="btn btn-secondary text-xs" data-export-add :disabled="busy||disabled||!data.active" @click="start">＋ 出荷を接続</button><button type="button" class="text-xs text-gray-500 underline" :disabled="busy||disabled||!data.active" @click="startOutcome">返品・取消を記録</button><label class="cursor-pointer text-xs text-primary-main underline" :class="busy||disabled?'pointer-events-none opacity-50':''">発送資料を追加<input type="file" accept="application/pdf" multiple class="sr-only" :disabled="busy||disabled" @change="upload"></label></div>
   <form v-if="form" class="mt-4 rounded-xl border border-gray-200 bg-gray-50 p-4 dark:border-white/10 dark:bg-white/5" @submit.prevent="save">
    <h4 class="text-sm font-semibold">{{ form.id?'出荷の確認':'Intrasの出荷を接続' }}</h4>
    <div class="mt-4 grid min-w-0 gap-3 sm:grid-cols-2">
     <label class="min-w-0 text-xs">Intras口座<input v-model="form.providerAccount" required maxlength="120" :readonly="!!form.id" class="draft-control mt-1" data-export-account></label>
     <label class="min-w-0 text-xs">出荷注文番号<input v-model="form.orderId" required maxlength="120" :readonly="!!form.id" class="draft-control mt-1" placeholder="OMJ10-…" data-export-order></label>
    </div>
    <button v-if="!form.id" type="button" class="mt-3 text-xs text-primary-main underline" :disabled="busy||!form.providerAccount||!form.orderId" @click="lookup">同じ出荷を検索して追加する</button>
    <div class="mt-4 grid min-w-0 gap-3 sm:grid-cols-2">
     <label class="min-w-0 text-xs">Intras申請書番号<input v-model="form.applicationId" maxlength="120" class="draft-control mt-1" data-export-application></label>
     <label class="min-w-0 text-xs">追跡番号<input v-model="form.tracking" required maxlength="120" class="draft-control mt-1" data-export-tracking></label>
     <label class="min-w-0 text-xs">出荷日<input v-model="form.shippedAt" required type="date" class="draft-control mt-1" data-export-date></label>
     <label class="min-w-0 text-xs">出荷全体の商品数<input v-model.number="form.itemCount" required type="number" min="1" max="1000" step="1" class="draft-control mt-1" data-export-quantity></label>
     <label class="min-w-0 text-xs">お客様の申告額（円）<input v-model.number="form.declaredAmount" required type="number" min="0" step="1" class="draft-control mt-1" data-export-declared></label>
     <p class="self-center text-xs leading-relaxed text-gray-500">お客様が申告した金額をそのまま保存します。購入金額から計算しません。</p>
     <label class="min-w-0 text-xs">輸出申告番号<input v-model="form.permitNumber" maxlength="120" class="draft-control mt-1" data-export-permit></label>
     <label class="min-w-0 text-xs">輸出許可日<input v-model="form.permitDate" type="date" class="draft-control mt-1" data-export-permit-date></label>
    </div>
    <fieldset class="mt-4"><legend class="text-xs font-medium">この出荷に含まれる在庫</legend><label v-for="unit in data.progress.units" :key="unit.inventoryId" class="mt-2 flex items-start gap-2 text-xs"><input v-model="selected" type="checkbox" :value="unit.inventoryId" :disabled="busy||!!unit.outcomeId||!!unit.exportId&&unit.exportId!==form.id" class="mt-0.5 rounded border-gray-300 text-primary-main" data-export-unit><span class="break-all">{{ unit.inventoryId }} · {{ unitLabel(unit.state) }}</span></label><p v-if="otherAllocations.length" class="mt-2 text-xs text-gray-500">他の購入から割当済みの {{ otherAllocations.length }}点もこの出荷に含めて保存します。</p></fieldset>
    <div class="mt-4 grid min-w-0 gap-3 sm:grid-cols-2"><div v-for="kind in ['invoice','permit']" :key="kind" class="min-w-0 text-xs"><label>{{ kind==='invoice'?'Invoice PDF':'輸出許可書 PDF' }}<select v-model="chosenDocs[kind]" class="draft-control mt-1" :data-export-document="kind"><option value="">未取得</option><option v-for="doc in documentOptions(kind)" :key="doc.value" :value="doc.value">{{ doc.name }}</option></select></label><button v-if="chosenDocs[kind]" type="button" class="mt-2 text-primary-main underline" :disabled="busy" @click="preview(kind)">選んだPDFをダウンロード</button></div></div>
    <label class="mt-4 flex items-start gap-2 text-xs leading-relaxed"><input v-model="form.confirmDocuments" type="checkbox" class="mt-0.5 rounded border-gray-300 text-primary-main" data-export-confirm-documents>両方の書類を開き、追跡番号・申告番号・商品数と、選んだ在庫がこの出荷に含まれることを確認した</label>
    <p class="mt-2 text-xs text-gray-500">書類の確認前でも保存できます。その場合は輸出完了に数えません。</p>
    <div class="mt-4 flex gap-3"><button class="btn btn-primary text-xs" :disabled="busy||disabled||!selected.length&&!otherAllocations.length" data-export-save>出荷と割当を保存</button><button type="button" class="text-xs text-gray-500 underline" :disabled="busy" @click="form=null">閉じる</button></div>
   </form>
   <form v-if="outcomeForm" class="mt-4 rounded-xl border border-gray-200 p-4 dark:border-white/10" @submit.prevent="saveOutcome"><h4 class="text-sm font-semibold">返品・取消の記録</h4><div class="mt-3 grid gap-3 sm:grid-cols-2"><label class="text-xs">在庫<select v-model="outcomeForm.inventoryId" required class="draft-control mt-1"><option value="">選択</option><option v-for="unit in data.progress.units.filter((u:any)=>!u.exportId&&!u.outcomeId)" :key="unit.inventoryId">{{ unit.inventoryId }}</option></select></label><label class="text-xs">結果<select v-model="outcomeForm.outcome" class="draft-control mt-1"><option value="returned">返品</option><option value="cancelled">取消</option></select></label></div><label class="mt-3 block text-xs">確認した理由<textarea v-model="outcomeForm.reason" required maxlength="1000" rows="2" class="draft-control mt-1" /></label><label class="mt-3 block text-xs">確認資料<select v-model="outcomeForm.document" required class="draft-control mt-1"><option value="">選択</option><option v-for="doc in data.documents" :key="doc.id" :value="doc.id">{{ doc.name }}</option></select></label><p class="mt-2 text-xs text-gray-500">この記録は輸出の代わりに結果を解決済みにします。返金・帳簿は別に確認してください。</p><div class="mt-4 flex gap-3"><button class="btn btn-primary text-xs" :disabled="busy||disabled">内容を確認して保存</button><button type="button" class="text-xs text-gray-500 underline" :disabled="busy" @click="outcomeForm=null">閉じる</button></div></form>
  </template>
 </section>
</template>
<script setup lang="ts">
import {useUserStore} from '~/stores/user'
const props=defineProps<{purchase:any;disabled:boolean}>(),user=useUserStore()
const data=ref<any>(null),error=ref(''),message=ref(''),busy=ref(false),form=ref<any>(null),selected=ref<string[]>([]),chosenDocs=ref<Record<string,string>>({invoice:'',permit:''}),outcomeForm=ref<any>(null)
let sequence=0,disposed=false
const base='/api/finance-exports',purchasePath=()=>base+'/purchases/'+props.purchase.id
const yen=(value:number)=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY'}).format(value)
const statusLabel=(s:string)=>({complete:'購入から輸出まで完了',resolved:'返品・取消を含めて解決済み',partial:'一部完了',pending:'輸出の照合待ち',conflict:'割当の確認が必要',purchase_evidence_pending:'購入原本の確認待ち',unlinked:'購入の接続解除済み'} as any)[s]
const unitLabel=(s:string)=>({exported:'輸出証憑 完了',documents_pending:'書類の確認待ち',pending:'出荷の接続待ち',returned:'返品確認済み',cancelled:'取消確認済み',conflict:'割当の確認が必要'} as any)[s]
const otherAllocations=computed(()=>(form.value?.allocations||[]).filter((a:any)=>a.purchaseId!==props.purchase.id))
async function load(){const ticket=++sequence;try{const r=await $fetch(purchasePath(),{headers:user.authHeader});if(!disposed&&ticket===sequence){data.value=r;error.value=''}}catch(e:any){if(!disposed&&ticket===sequence)error.value=e.data?.data?.message||'輸出の進捗を読み込めません。'}}
async function action(fn:()=>Promise<void>){busy.value=true;error.value='';message.value='';try{await fn()}catch(e:any){error.value=e.data?.data?.message||e.data?.message||e.message||'保存できません。'}finally{busy.value=false}}
function start(){form.value={revision:0,providerAccount:'',orderId:'',applicationId:'',tracking:'',shippedAt:'',itemCount:1,declaredAmount:null,permitNumber:'',permitDate:'',allocations:[],documents:[],confirmDocuments:false};selected.value=[];chosenDocs.value={invoice:'',permit:''};outcomeForm.value=null}
function edit(r:any){const allocations=r.status==='active'?r.allocations:[];form.value={id:r.id,revision:r.revision,providerAccount:r.providerAccount,orderId:r.orderId,applicationId:r.applicationId||'',tracking:r.tracking,shippedAt:r.shippedAt,itemCount:r.itemCount,declaredAmount:r.declaredValue.amount,permitNumber:r.permitNumber||'',permitDate:r.permitDate||'',allocations,documents:r.documents,confirmDocuments:false};selected.value=allocations.filter((a:any)=>a.purchaseId===props.purchase.id).map((a:any)=>a.inventoryId);chosenDocs.value=Object.fromEntries(['invoice','permit'].map(kind=>[kind,r.documents.some((d:any)=>d.kind===kind)?'saved:'+kind:'']));outcomeForm.value=null}
async function lookup(){await action(async()=>{const r:any=await $fetch(base+'/lookup',{headers:user.authHeader,query:{account:form.value.providerAccount,order:form.value.orderId}});if(r.record){edit(r.record);message.value='既存の出荷を読み込みました。この購入の在庫を選んで追加できます。'}else message.value='保存済みの出荷はありません。新しく登録できます。'})}
function documentOptions(kind:string){const kept=form.value?.documents.find((d:any)=>d.kind===kind);return [...(kept?[{value:'saved:'+kind,name:'保管済み · '+kept.name}]:[]),...(data.value?.documents||[]).filter((d:any)=>d.kind==='shipping'&&d.mimeType==='application/pdf').map((d:any)=>({value:d.id,name:d.name}))]}
function documentInput(value:string,kind:string){if(value.startsWith('saved:'))return {kind,hash:form.value.documents.find((d:any)=>d.kind===kind).hash};const d=data.value.documents.find((d:any)=>d.id===value);return {kind,hash:d.hash,...(d.upload?{uploadId:d.id}:{sourceDocumentId:d.id})}}
async function preview(kind:string){const value=chosenDocs.value[kind];if(value.startsWith('saved:'))return download(form.value,form.value.documents.find((d:any)=>d.kind===kind));const d=data.value.documents.find((d:any)=>d.id===value);await action(async()=>{const blob:any=await $fetch(d.url,{headers:user.authHeader,responseType:'blob'});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=d.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)})}
async function save(){await action(async()=>{const {allocations,documents,...fields}=form.value;await $fetch(base+'/save',{method:'POST',headers:user.authHeader,body:{...fields,confirm:true,allocations:[...otherAllocations.value.map((a:any)=>({purchaseId:a.purchaseId,inventoryId:a.inventoryId})),...selected.value.map(inventoryId=>({purchaseId:props.purchase.id,inventoryId}))],documents:['invoice','permit'].filter(k=>chosenDocs.value[k]).map(k=>documentInput(chosenDocs.value[k],k))}});form.value=null;await load();message.value='出荷と在庫の割当を保存しました。'})}
async function release(r:any){if(!window.confirm('この出荷に含まれる'+r.allocations.length+'点すべての割当を解除します。原本は保管されます。'))return;await action(async()=>{await $fetch(base+'/'+r.id+'/release',{method:'POST',headers:user.authHeader,body:{revision:r.revision,confirm:true}});form.value=null;await load()})}
async function download(r:any,d:any,outcome=false){await action(async()=>{const blob:any=await $fetch(base+'/'+(outcome?'outcomes/':'')+r.id+'/originals/'+d.hash,{headers:user.authHeader,responseType:'blob'});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=d.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)})}
async function upload(event:Event){const input=event.target as HTMLInputElement,files=[...(input.files||[])];await action(async()=>{for(const file of files){if(file.size>10485760||file.type!=='application/pdf')throw Error('10MB以内のPDFを選択してください。');data.value=await $fetch(purchasePath()+'/documents',{method:'POST',headers:{...user.authHeader,'Content-Type':'application/pdf'},query:{name:file.name},body:file})}message.value='PDFを保管しました。出荷のInvoice・許可書として選択できます。'});input.value=''}
function startOutcome(){outcomeForm.value={inventoryId:'',outcome:'returned',reason:'',document:''};form.value=null}
async function saveOutcome(){await action(async()=>{const d=data.value.documents.find((d:any)=>d.id===outcomeForm.value.document);data.value=await $fetch(purchasePath()+'/outcomes',{method:'POST',headers:user.authHeader,body:{inventoryId:outcomeForm.value.inventoryId,outcome:outcomeForm.value.outcome,reason:outcomeForm.value.reason,revision:data.value.outcomeRevisions[outcomeForm.value.inventoryId]||0,confirm:true,document:{hash:d.hash,...(d.upload?{uploadId:d.id}:{sourceDocumentId:d.id})}}});outcomeForm.value=null;message.value='返品・取消の結果を保存しました。'})}
async function releaseOutcome(r:any){if(!window.confirm('返品・取消の確認を解除し、この在庫を照合待ちに戻します。'))return;await action(async()=>{await $fetch(base+'/outcomes/'+r.id+'/release',{method:'POST',headers:user.authHeader,body:{revision:r.revision,confirm:true}});await load()})}
onMounted(load)
watch(()=>[props.purchase.id,props.purchase.revision],()=>{form.value=null;outcomeForm.value=null;load()})
onBeforeUnmount(()=>{disposed=true;++sequence})
</script>
