<template>
  <section v-if="busy || error || rows.length || message" class="card mb-6 p-4 sm:p-6" data-service-mapping-review>
    <div class="flex flex-wrap items-start justify-between gap-3"><div><h2 class="text-base font-semibold text-gray-900 dark:text-gray-100">サービス利用料をまとめて確認</h2><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">会社経費のうち、科目を提案できる利用料 {{ rows.length }}件</p></div><button type="button" class="btn btn-secondary text-xs" :disabled="busy" @click="load">候補を更新</button></div>
    <p v-if="error" role="alert" class="mt-3 break-words text-sm text-red-600">{{ error }}</p><p v-if="message" role="status" class="mt-3 text-sm text-green-700 dark:text-green-400">{{ message }}</p>
    <p v-if="busy && !rows.length" class="mt-3 text-sm text-gray-500" role="status">候補を確認しています…</p>
    <p v-if="truncated" class="mt-3 text-xs text-amber-700">サービス名に該当する先頭60件から表示しています。取込明細を絞ると残りも確認できます。</p>
    <template v-if="rows.length">
      <p class="mt-3 text-sm leading-relaxed text-gray-600 dark:text-gray-300">利用先の表記と現在の会社経費の分類から、空欄への候補を用意しました。対象を選び、業務での利用を確認して下書きに保存できます。</p>
      <div class="mt-4 flex flex-wrap gap-3"><button type="button" class="py-2 text-xs text-primary-main" data-select-all-services :disabled="busy" @click="selected=rows.slice(0,30).map(identity);confirmed=false">{{ rows.length>30?'先頭30件':'すべて' }}を選択</button><button type="button" class="py-2 text-xs text-gray-500" :disabled="busy" @click="selected=[];confirmed=false">選択を解除</button><span class="py-2 text-xs text-gray-500">{{ selected.length }}件選択</span></div>
      <div class="mt-2 divide-y divide-gray-200 border-y border-gray-200 dark:divide-white/10 dark:border-white/10">
        <article v-for="row in rows" :key="identity(row)" class="py-4" :data-service-line="row.line">
          <div class="flex items-start gap-3"><input v-model="selected" type="checkbox" :value="identity(row)" :aria-label="row.merchant+' '+row.date+'を選択'" :disabled="busy || selected.length>=30&&!selected.includes(identity(row))" class="mt-1 rounded border-gray-300 text-primary-main" @change="confirmed=false"><div class="min-w-0 flex-1"><div class="flex flex-wrap justify-between gap-2"><h3 class="break-words text-sm font-medium text-gray-900 dark:text-gray-100">{{ row.merchant }}</h3><span class="text-sm tabular-nums">{{ yen(row.amount) }}</span></div><p class="mt-1 text-xs text-gray-500">{{ row.date }} · {{ row.card }}</p>
          <dl class="mt-3 grid gap-2 sm:grid-cols-2"><div v-for="field in row.fields" :key="field.key" class="rounded-lg bg-gray-50 p-3 dark:bg-white/5"><dt class="text-xs text-gray-500">{{ field.label }}</dt><dd class="mt-1 text-sm"><span class="text-gray-400">空欄</span><span class="mx-2 text-gray-400">→</span><strong class="font-medium text-gray-900 dark:text-gray-100">{{ field.displayValue }}</strong></dd></div></dl><p v-if="row.fields.length===1" class="mt-2 text-xs text-gray-500">区分は「{{ row.currentCategory }}」が入力されています。</p>
          <details class="mt-3 text-xs text-gray-500 dark:text-gray-400"><summary class="cursor-pointer py-1 text-primary-main">候補の根拠</summary><p class="mt-2 leading-relaxed">{{ row.mappingReason }}</p><p class="mt-2 leading-relaxed">{{ row.reason }}</p><div class="mt-2 flex flex-wrap gap-3"><a v-for="source in row.sources" :key="source.url" :href="source.url" target="_blank" rel="noopener noreferrer" class="text-primary-main underline">{{ source.title }}</a></div></details>
          <NuxtLink :to="'/mapping-draft/'+row.importId+'/'+row.line" class="mt-2 inline-block py-2 text-xs text-primary-main">別の科目・個別の内容を確認 →</NuxtLink></div></div>
        </article>
      </div>
      <div class="mt-4 rounded-xl bg-gray-50 p-4 dark:bg-white/5"><label class="flex items-start gap-3 text-sm leading-relaxed text-gray-700 dark:text-gray-300"><input v-model="confirmed" type="checkbox" data-confirm-service-use :disabled="busy || !selected.length" class="mt-1 rounded border-gray-300 text-primary-main"><span>{{ confirmation }}</span></label><button type="button" class="btn btn-primary mt-4 text-sm" data-save-services :disabled="busy || !selected.length || !confirmed" @click="save">{{ selected.length }}件の候補を確認して下書きに保存</button><p class="mt-3 text-xs leading-relaxed text-gray-500">税区分・税率・インボイスの確認は、各下書きで続けられます。帳簿への登録は下書き全体の確認後に行います。</p></div>
    </template>
  </section>
</template>
<script setup lang="ts">
import {useUserStore} from '~/stores/user'
const props=defineProps<{importIds:string[]}>(),emit=defineEmits<{saved:[]}>(),user=useUserStore(),rows=ref<any[]>([]),busy=ref(false),error=ref(''),message=ref(''),selected=ref<string[]>([]),confirmed=ref(false),confirmation=ref(''),truncated=ref(false)
const identity=(r:any)=>r.importId+':'+r.line,yen=(n:number)=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY'}).format(n)
let generation=0
async function load(){const run=++generation;busy.value=true;error.value='';selected.value=[];confirmed.value=false;try{const response:any=await $fetch('/api/finance-service-review',{headers:user.authHeader,query:{imports:props.importIds.join(',')}});if(run!==generation)return;rows.value=response.rows;confirmation.value=response.confirmation;truncated.value=response.truncated}catch(e:any){if(run===generation){rows.value=[];error.value=e.data?.data?.message||e.data?.statusMessage||'候補を読み込めませんでした。'}}finally{if(run===generation)busy.value=false}}
async function save(){if(busy.value||!confirmed.value||!selected.value.length)return;busy.value=true;error.value='';message.value='';const choices=rows.value.filter(r=>selected.value.includes(identity(r))).map(r=>({importId:r.importId,line:r.line,key:r.key}));try{const result:any=await $fetch('/api/finance-service-review',{method:'POST',headers:user.authHeader,body:{rows:choices,confirmServiceUse:true}});message.value=(result.saved+result.alreadySaved)+'件を下書きに保存しました。'+(result.failed?result.failed+'件は再確認が必要です。':'');await load();if(result.failed)error.value=result.results.filter((r:any)=>r.state==='failed').map((r:any)=>'明細 '+r.line+': '+r.message).join(' ');emit('saved')}catch(e:any){error.value=e.data?.data?.message||e.data?.statusMessage||'保存結果を確認できませんでした。同じ選択で再試行できます。'}finally{busy.value=false}}
watch(()=>props.importIds.join(','),()=>{message.value='';load()},{immediate:true});onBeforeUnmount(()=>{generation++})
</script>
