import {randomUUID,createHash} from 'node:crypto';
import {browserApi} from '../research-worker/sheets.mjs';
import {connectSheetBrowser} from '../research-worker/sheet-export.mjs';
import {parseIntrasDocuments,verifyIntrasPdfReadback,documentVerificationSchema,documentVerificationSystem} from '../shared/finance-workflow-documents.mjs';
import {interpret} from './interpreter.mjs';
const hash=v=>createHash('sha256').update(v).digest('hex');
const fail=(code,message)=>{const e=Error(message);e.code=code;throw e};

// Capture the PDF generated by Intras's native download button in this tab.
// No browser-wide download directory or behaviour is changed.
export async function nativeInvoiceBytes(page) {
 if(await page.$$eval('.page',nodes=>nodes.length)!==1)fail('source_incomplete','Multiple invoice pages need review');
 await page.evaluate(()=>{
  window.__omfPdfCapture={promise:null};const original=URL.createObjectURL.bind(URL);
  URL.createObjectURL=blob=>{if(blob instanceof Blob&&blob.type==='application/pdf')window.__omfPdfCapture.promise=blob.arrayBuffer().then(buffer=>{let binary='';for(const byte of new Uint8Array(buffer))binary+=String.fromCharCode(byte);return btoa(binary)});return original(blob)};
  // FileSaver can click a detached anchor, which never reaches document listeners.
  const dispatch=HTMLAnchorElement.prototype.dispatchEvent,click=HTMLAnchorElement.prototype.click;
  HTMLAnchorElement.prototype.dispatchEvent=function(e){if(e.type==='click'&&this.href.startsWith('blob:')&&window.__omfPdfCapture.promise)return false;return dispatch.call(this,e)};
  HTMLAnchorElement.prototype.click=function(){if(this.href.startsWith('blob:')&&window.__omfPdfCapture.promise)return;return click.call(this)};
 });
 await page.click('button[onclick="topdfall();"]');
 await page.waitForFunction(()=>window.__omfPdfCapture?.promise!==null,{timeout:45000});
 const base64=await page.evaluate(()=>window.__omfPdfCapture.promise);
 const bytes=Buffer.from(base64,'base64');if(bytes.length>10485760||bytes.subarray(0,5).toString()!=='%PDF-')fail('integrity_failed','Native invoice PDF is invalid');
 return bytes;
}

export class IntrasCollector {
 constructor(config,{open=browserApi,connect=connectSheetBrowser,interpretDocuments=interpret}={}) {this.config=config;this.open=open;this.connect=connect;this.interpret=interpretDocuments;this.lastLoginAttempt=0;}
 async collect(target) {
  const connection=this.config.workflow?.intras;
  if(!connection||connection.account!=='ohmyjapan1'||!/^[-\w]{1,80}$/.test(connection.profile||'')||target.providerAccount!==connection.account)fail('connection_required','Intras connection is not configured');
  if(!/^[A-Z0-9]+-[A-Z0-9]+$/.test(target.orderId)||!/^\d{6,30}$/.test(target.tracking.replace(/[-\s]/g,'')))fail('conflict','Invalid shipment identity');
  const url='https://intras.co.jp/mypage/delivery?referCode='+encodeURIComponent(target.orderId),opened=await this.open('open',{url,profile:connection.profile,wait_for_cf:false});
  let browser,page;const tabs=[];
  try {
   if(!String(opened.url).startsWith('https://intras.co.jp/mypage/delivery'))fail('connection_required','Intras sign-in required');
   const marker=randomUUID();await this.open('eval',{session_id:opened.session_id,script:'window.__omfIntrasRead='+JSON.stringify(marker)});browser=await this.connect(connection.profile);
   for(const p of await browser.pages())if(p.url().startsWith('https://intras.co.jp/mypage/delivery')&&await p.evaluate(v=>window.__omfIntrasRead===v,marker)){page=p;break}
   if(!page)fail('connection_required','Authorized Intras tab unavailable');
   await page.waitForNetworkIdle({timeout:30000});
   if(await page.$('form[name="form-member-login"]')) {
    if(!connection.username||!connection.password||connection.username!==connection.account||Date.now()-this.lastLoginAttempt<30000)fail('connection_required','Intras sign-in required');
    this.lastLoginAttempt=Date.now();
    const form=await page.$('form[name="form-member-login"]');
    if(await form.evaluate(f=>new URL(f.action,location.href).href)!=='https://intras.co.jp/member/login-ok')fail('connection_required','Intras sign-in form changed');
    await page.$eval('form[name="form-member-login"] input[name="id"]',e=>e.value='');await page.type('form[name="form-member-login"] input[name="id"]',connection.username);
    await page.$eval('form[name="form-member-login"] input[name="passwd"]',e=>e.value='');await page.type('form[name="form-member-login"] input[name="passwd"]',connection.password);
    await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded',timeout:30000}),form.evaluate(f=>f.requestSubmit())]);
    await page.goto(url,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForNetworkIdle({timeout:30000});
    if(await page.$('input[type="password"]'))fail('connection_required','Intras sign-in needs attention');
   }
   const rows=await page.evaluate(()=>[...document.querySelectorAll('input[name="checkNo[]"]')].map(e=>({applicationId:e.value,text:e.closest('tr')?.innerText||''})));
   if(!rows.length) {
    if(!await page.$('form[name="form-option-extend"]')||page.url()!==url)fail('connection_required','The authenticated delivery search could not be verified');
    const e=Error('No matching delivery row in the authenticated search');e.code='missing_documents';e.attempt={kind:'delivery_not_found',url,capturedAt:new Date().toISOString(),rows:[],formPresent:true,html:await page.content()};throw e;
   }
   if(rows.length!==1||!/^\d{4,20}$/.test(rows[0].applicationId)||!rows[0].text.includes(target.orderId)||!rows[0].text.replace(/[-\s]/g,'').includes(target.tracking.replace(/[-\s]/g,'')))fail('conflict','Intras delivery search identity is ambiguous');
   const bound={...target,applicationId:rows[0].applicationId},documents=[];
   for(const kind of ['invoice','export']) {
    await page.click('input[name="pdfMode"][value="1"]');
    const box=await page.$('input[name="checkNo[]"][value="'+bound.applicationId+'"]');if(!box)fail('conflict','Intras selection changed');if(!await box.evaluate(e=>e.checked))await box.click();
    await page.select('select[name="pdfType"]',kind);
    await page.evaluate(()=>document.forms['form-option-extend'].querySelectorAll('input[name=pdfType],input[name=pdfMode],input[name=textType],input[name=checkNo]').forEach(e=>e.remove()));
    const known=new Set(browser.targets()),created=browser.waitForTarget(t=>!known.has(t)&&t.opener()===page.target(),{timeout:30000});
    await page.click('.event-click-pdf-view');const tab=await(await created).page();tabs.push(tab);await tab.waitForNetworkIdle({timeout:30000});await tab.evaluate(()=>document.fonts.ready);
    if(new URL(tab.url()).origin!=='https://intras.co.jp')fail('conflict','Intras print view left its origin');
    const text=await tab.evaluate(()=>document.body.innerText),html=await tab.content();
    if(text.length>150000||html.length>2000000)fail('source_incomplete','Intras print view exceeds bounds');
    const bytes=kind==='invoice'?await nativeInvoiceBytes(tab):Buffer.from(await tab.pdf({format:'A4',preferCSSPageSize:true,printBackground:true,displayHeaderFooter:false,margin:{top:0,bottom:0,left:0,right:0}}));
    if(bytes.length>10485760||bytes.subarray(0,5).toString()!=='%PDF-')fail('integrity_failed','Invalid Intras PDF');
    documents.push({kind:kind==='invoice'?'invoice':'permit',name:target.orderId+'-'+(kind==='invoice'?'invoice':'export-permit')+'.pdf',bytes,hash:hash(bytes),mimeType:'application/pdf',sourceUrl:tab.url(),captureMethod:kind==='invoice'?'native_intras_pdf':'official_print_view',capturedAt:new Date().toISOString(),text,html});await tab.close();
   }
   let parsed;try{parsed=parseIntrasDocuments(bound,documents[0].text,documents[1].text)}catch(e){fail('conflict',e.message)}
   const readback=await this.interpret(this.config,{system:documentVerificationSystem,schema:documentVerificationSchema,input:{documentOrder:['invoice','permit']},documents});
   try{verifyIntrasPdfReadback(parsed,readback.value)}catch(e){fail('integrity_failed',e.message)}
   return {target:bound,parsed,documents:documents.map(d=>({...d,base64:d.bytes.toString('base64'),bytes:undefined})),readback:readback.value,models:readback.models,delivery:{url,text:rows[0].text,capturedAt:new Date().toISOString()}};
  } finally {for(const tab of tabs)await tab.close().catch(()=>{});try{if(browser)await browser.disconnect()}finally{await this.open('close',{session_id:opened.session_id}).catch(()=>{})}}
 }
}
