export const purposeContract:string;
export const numericValueContract:string;
export function validationFeedback(error:any):any;
export function validateDiagnostic(input:any):{code:string;correctionAttempted:boolean};
export function diagnosticMessage(input:any):string;
export const researchFields: any[];
export const reportSchema: any;
export function validateSources(input: any): any[];
export function validateReport(raw: any, context: any, sources: any[]): any;
export function parseRegistry(raw: any, number: string, date: string): any;
