import test from 'node:test';import assert from 'node:assert/strict';
import {customerGoodsContext,customerPurchaseCandidate,customerReviewBinding,customerReviewApplied,customerReviewGroup} from '../shared/finance-customer-review.mjs';
import {purchaseAccountHistory} from '../shared/finance-purchase-accounts.mjs';
import {consultationEvidence} from '../shared/finance-consultation.mjs';
const customer='a'.repeat(24),account='b'.repeat(24),category='c'.repeat(24),make=()=>({importId:'d'.repeat(24),line:2,key:'source-key',sourceHash:'source-hash',revision:0,source:{kind:'expense',description:'Synthetic goods shop',category:'商品代金',account:{id:'e'.repeat(24),name:'Synthetic card'}},values:{purpose:'customer',customerId:customer,accountCategoryId:'',subAccountCategoryId:'',transactionCategoryId:category,productName:'',items:[],taxRate:null,taxCategoryId:''},references:{customers:[{_id:customer,name:'Synthetic customer',isActive:true}],accountCategories:[{_id:account,name:'仕入高',type:'expense'}],transactionCategories:[{_id:category,name:'商品代金'}]},evidence:{},rememberedFields:[]});
test('customer goods need an explicit treatment and fill only a blank purchase account',()=>{const d=make();assert.equal(customerPurchaseCandidate(d,''),null);assert.equal(customerPurchaseCandidate(d,'advance'),null);const p=customerPurchaseCandidate(d,'resale');assert.deepEqual(p.fields,[{key:'accountCategoryId',label:'勘定科目',before:'',value:account,displayValue:'仕入高'}]);assert.ok(p.confirmation.includes('自社の売上'));assert.equal(d.values.accountCategoryId,'');d.references.accountCategories.push({_id:'f'.repeat(24),name:'立替金',type:'asset'});assert.ok(customerPurchaseCandidate(d,'advance').confirmation.includes('同額を回収'))});
test('existing accounts, unclear purpose, locked and remembered rows require individual review',()=>{for(const patch of [{purpose:'company'},{purpose:'unresolved'},{customerId:''},{accountCategoryId:account},{subAccountCategoryId:account},{transactionCategoryId:''}]){const d=make();Object.assign(d.values,patch);assert.equal(customerGoodsContext(d),null)}for(const patch of [{locked:true},{approvedAt:'2026-08-01'},{rememberedFields:['taxRate']},{purchaseHistory:{status:'review'}}])assert.equal(customerGoodsContext({...make(),...patch}),null)});
test('shipping, services, conflicting evidence, non-expenses and inactive customers are excluded',()=>{for(const modify of [d=>{d.source.description='ヤマト運輸 Synthetic'},d=>{d.source.description='HEROKU* TEST'},d=>{d.source.description='ブックオフ Synthetic'},d=>{d.source.kind='credit'},d=>{d.source.category='通信費'},d=>{d.references.customers[0].isActive=false},d=>{d.evidence.customerId={state:'conflict'}},d=>{d.evidence.accountCategoryId={alternative:account}}]){const d=make();modify(d);assert.equal(customerGoodsContext(d),null)}});
test('wrong-type, subsidiary, inactive and ambiguous account references cannot become choices',()=>{for(const modify of [d=>{d.references.accountCategories[0].type='asset'},d=>{d.references.accountCategories[0].parentId=customer},d=>{d.references.accountCategories[0].isActive=false},d=>{d.references.accountCategories.push({...d.references.accountCategories[0],_id:'f'.repeat(24)})}]){const d=make();modify(d);assert.equal(customerPurchaseCandidate(d,'resale'),null)}});
test('groups keep cards and customers distinct while normalizing exact merchant spelling',()=>{const c=customerGoodsContext(make()),key=customerReviewGroup(c);assert.equal(customerReviewGroup({...c,merchant:'SYNTHETIC GOODS SHOP'}),key);for(const patch of [{customerId:'f'.repeat(24)},{accountId:'f'.repeat(24)},{merchant:'Other shop'}])assert.notEqual(customerReviewGroup({...c,...patch}),key)});
test('binding and idempotence protect the exact draft revision, evidence context and selected treatment',()=>{const d=make(),p=customerPurchaseCandidate(d,'resale'),key=customerReviewBinding(d,p);for(const patch of [{revision:1},{values:{...d.values,notes:'changed'}},{cardAccounting:{key:'changed'}}])assert.notEqual(customerReviewBinding({...d,...patch},p),key);d.revision=1;d.values.accountCategoryId=account;d.history=[{revision:1,customerReview:{...p,key:'saved-key'}}];assert.equal(customerReviewApplied(d,'saved-key','resale'),true);assert.equal(customerReviewApplied(d,'saved-key','advance'),false);assert.equal(customerReviewApplied({...d,revision:2},'saved-key','resale'),false)});
test('consultation receives the confirmed accounting explanation without needing a new question',()=>{const d=make(),p=customerPurchaseCandidate(d,'resale');d.values.accountCategoryId=account;d.evidence.accountCategoryId={state:'confirmed',source:'user',reason:p.confirmation,customerReview:{treatment:'resale'}};const c=consultationEvidence(d);assert.equal(c.fields.find(f=>f.key==='accountCategoryId').evidence.reason,p.confirmation)});

const withUnlinkedHistory=()=>{const d=make();d.source.purchaseDate='2026-08-01';const bundle={version:1,sourceHash:'1'.repeat(64),items:[{merchant:'synthetic goods shop',date:'2025-11-01',amount:100,accountCategoryId:account,subAccountCategoryId:'',accountName:'仕入高',subAccountName:'',purpose:'unresolved',customerId:'',disposition:'review',sourceRows:[]}]};d.purchaseHistory=purchaseAccountHistory(bundle,d.source,d.values,d.references);return d};
test('current customer goods can be explicitly reviewed while unlinked journal context remains unverified',()=>{const d=withUnlinkedHistory(),p=customerPurchaseCandidate(d,'resale');assert.equal(p.context.historyGap.code,'unlinked_context');assert.equal(d.purchaseHistory.status,'review');assert.equal(d.values.accountCategoryId,'');assert.equal(customerPurchaseCandidate(d,''),null);d.evidence.customerId={state:'conflict'};assert.equal(customerPurchaseCandidate(d,'resale'),null)});
test('history-gap provenance is part of the save binding and incomplete gap markers cannot unblock a row',()=>{const d=withUnlinkedHistory(),p=customerPurchaseCandidate(d,'resale'),key=customerReviewBinding(d,p);d.purchaseHistory.sourceHash='2'.repeat(64);assert.notEqual(customerReviewBinding(d,customerPurchaseCandidate(d,'resale')),key);for(const patch of [{reviewCode:'different_context'},{sourceHash:''},{exampleCount:0}]){const changed=withUnlinkedHistory();Object.assign(changed.purchaseHistory,patch);assert.equal(customerPurchaseCandidate(changed,'resale'),null)}});
