import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {validateDocumentExtraction,documentReading,documentSuggestions,matchDocumentRecords,documentConsultation} from '../shared/finance-document-evidence.mjs';
import {documentCycle} from '../teaching-worker/document-worker.mjs';
const make=(extra=[])=>{const fields=[{key:'merchant',value:'架空商店',page:1,quote:'架空商店'},{key:'date',value:'2026-08-01',page:1,quote:'2026年08月01日'},{key:'total',value:'2200',page:1,quote:'合計 2,200円'},{key:'currency',value:'JPY',page:1,quote:'合計 2,200円'},{key:'taxRate',value:'10',page:1,quote:'税率10%'},...extra];return {complete:true,pages:[{page:1,text:fields.map(f=>f.quote).join('\n')}],records:[{fields}]}};
const ready=(raw=make())=>({state:'ready',...validateDocumentExtraction(raw)}),row=(line=2)=>({line,kind:'expense',amount:2200,currency:'JPY',purchaseDate:'2026-08-01',processingDate:'2026-08-03',description:'架空商店'});
test('literal Japanese dates, amounts, invoice identifiers and zero tax keep page/quote provenance',()=>{const r=validateDocumentExtraction(make([{key:'invoiceNumber',value:'T1234567890123',page:1,quote:'登録番号 T1234567890123'}]));assert.equal(r.records[0].fields[2].value,2200);const z=make();z.records[0].fields[4]={key:'taxRate',value:'0',page:1,quote:'税率0%'};z.pages[0].text+='\n税率0%';assert.equal(documentSuggestions(validateDocumentExtraction(z).records[0]).find(f=>f.key==='taxRate').value,0)});
test('invented quote/value, wrong dates, unprinted tax and arbitrary fields are rejected',()=>{for(const change of [f=>f.quote='Not on page',f=>f.value='9999',f=>f.key='accountCategoryId']){const r=make();change(r.records[0].fields[2]);assert.throws(()=>validateDocumentExtraction(r))}const r=make();r.records[0].fields[1].value='2026-02-30';assert.throws(()=>validateDocumentExtraction(r));const t=make();t.records[0].fields[4].quote='合計 2,200円';assert.throws(()=>validateDocumentExtraction(t));const n=make([{key:'invoiceNumber',value:'T123',page:1,quote:'T123'}]);assert.throws(()=>validateDocumentExtraction(n))});
test('mixed rates and multiple products never collapse into one transaction suggestion',()=>{const r=ready(make([{key:'taxRate',value:'8',page:1,quote:'軽減8%'},{key:'productName',value:'ノート',page:1,quote:'ノート'},{key:'productName',value:'お茶',page:1,quote:'お茶'}]));assert.ok(!documentSuggestions(r.records[0]).some(f=>['taxRate','productName'].includes(f.key)))});
test('exact matches stay candidates; duplicate purchases, conflicts and amount alone do not auto-resolve',()=>{assert.equal(matchDocumentRecords(ready(),[row()])[0].status,'candidate');assert.equal(matchDocumentRecords(ready(),[row(),row(3)])[0].status,'ambiguous');assert.equal(matchDocumentRecords(ready(),[{...row(),currency:'USD'}])[0].status,'review');assert.equal(matchDocumentRecords(ready(),[{...row(),description:'Elsewhere',purchaseDate:'2026-08-09'}])[0].status,'unmatched');assert.equal(matchDocumentRecords(ready(),[{...row(),kind:'repayment'}])[0].status,'unmatched');assert.deepEqual(matchDocumentRecords({...ready(),complete:false},[row()]),[])});
test('identifier matches surface contradictory amounts and dates for review',()=>{const r=ready(make([{key:'receiptNumber',value:'TEST-721',page:1,quote:'注文 TEST-721'}]));const m=matchDocumentRecords(r,[{...row(),amount:999,purchaseDate:'2026-08-05'}],{2:{receiptNumber:'TEST-721'}})[0];assert.equal(m.status,'review');assert.equal(m.matches[0].conflicts.length,2)});
test('stale hashes suppress reading; AI receives bounded excerpts, no page transcript or unearned association',()=>{const canonical=validateDocumentExtraction(make());assert.equal(documentReading({hash:'b',extraction:{hash:'a',state:'ready',result:canonical}}).state,'stale');const reading=documentReading({hash:'a',extraction:{hash:'a',state:'ready',result:canonical}});const doc={id:'test',hash:'a',reading,kind:'receipt'},e=documentConsultation([doc]);assert.equal(e[0].verified,false);assert.equal(e[0].associationReviewed,false);assert.ok(!JSON.stringify(e).includes('pages'));assert.equal(documentConsultation([doc],{taxRate:{documentId:'test',extraction:{hash:'a',record:0}}})[0].associationReviewed,true)});
test('worker downloads only assigned bytes with no redirects and never interprets a hash mismatch',async()=>{for(const corrupt of [false,true]){const bytes=Buffer.from('synthetic bytes'),calls=[],job={id:'a'.repeat(24),lease:'test-lease',hash:createHash('sha256').update(corrupt?'other':bytes).digest('hex'),size:bytes.length,mimeType:'application/pdf'};let interpreted=false;const worker={origin:'http://127.0.0.1:8080',config:{token:'synthetic'},log(){},async api(){},async request(url,options){calls.push({url,options});if(url.endsWith('/claim'))return Response.json({job});if(url.includes('/file?'))return new Response(bytes);return Response.json({success:true})}};await documentCycle(worker,async()=>{interpreted=true;return validateDocumentExtraction(make())});assert.equal(interpreted,!corrupt);assert.ok(calls.every(c=>c.options.redirect==='error'));const result=JSON.parse(calls.at(-1).options.body);assert.equal(result.failed===true,corrupt);assert.ok(calls.every(c=>c.url.startsWith(worker.origin+'/api/finance-documents/worker/')))}});

test('printed percentage suffix normalizes only with literal percent evidence',()=>{const raw=make();raw.records[0].fields[4].value='10%';assert.equal(validateDocumentExtraction(raw).records[0].fields[4].value,10);raw.complete=false;assert.throws(()=>validateDocumentExtraction(raw))});
