import { randomUUID } from 'node:crypto'
import { FinanceDocument, FinanceDraft } from '../models/FinanceDraft'
import { FinanceChatAgent } from '../models/FinanceChat'
import { fail,id,ownedImport,ownedAccount } from './financeService'
import { readDraft,saveDraft,addDocument,downloadDocument } from './financeDraftService'
import { documentReading,documentDisplayReading,matchDocumentRecords,validateDocumentExtraction } from '../../shared/finance-document-evidence.mjs'
const live = ['queued','working']
async function owned(ownerId:string,documentId:string):Promise<any>{const doc=await FinanceDocument.findOne({_id:id(documentId),ownerId}).lean();if(!doc)fail(404,'書類が見つかりません。');return doc}
function publicDoc(doc:any){return {id:String(doc._id),name:doc.name,kind:doc.kind,mimeType:doc.mimeType,size:doc.size,hash:doc.hash,importId:String(doc.importId),line:doc.line,selectedRecord:doc.selectedRecord || null,reading:documentDisplayReading(doc)}}
async function context(ownerId:string,importId:string){const batch=await ownedImport(ownerId,importId),saved:any[]=await FinanceDraft.find({ownerId,importId}).select('line values.receiptNumber values.trackingNumber').lean();return {batch,values:Object.fromEntries(saved.map(d=>[d.line,d.values]))}}
export async function documentDetail(ownerId:string,documentId:string){const doc=await owned(ownerId,documentId),ctx=await context(ownerId,String(doc.importId)),result=publicDoc(doc);return {...result,matches:matchDocumentRecords(result.reading,ctx.batch.rows,ctx.values),connected:!!await FinanceChatAgent.exists({ownerId,accountIds:doc.accountId,documentEnabled:true,enabled:true,revokedAt:null,lastSeenAt:{$gt:new Date(Date.now()-65000)}})}}
export async function documentBatch(ownerId:string,importId:string){const ctx=await context(ownerId,importId),docs:any[]=await FinanceDocument.find({ownerId,importId}).sort({createdAt:-1}).limit(101).lean();const unique=new Map<string,any>();for(const doc of docs.slice(0,100)){const key=doc.hash,previous=unique.get(key);if(previous){previous.attachedLines.push(doc.line);continue}const view=publicDoc(doc);unique.set(key,{...view,attachedLines:[doc.line],matches:matchDocumentRecords(view.reading,ctx.batch.rows,ctx.values)})}return {documents:[...unique.values()],truncated:docs.length>100}}
export async function queueDocument(ownerId:string,documentId:string,body:any){const doc=await owned(ownerId,documentId);await ownedAccount(ownerId,String(doc.accountId));if(body?.hash!==doc.hash)fail(409,'書類を再読込してください。');if(['ready',...live].includes(documentReading(doc).state))return documentDetail(ownerId,documentId);if(!await FinanceChatAgent.exists({ownerId,accountIds:doc.accountId,documentEnabled:true,enabled:true,revokedAt:null,lastSeenAt:{$gt:new Date(Date.now()-65000)}}))fail(409,'書類の読み取りに接続できません。');if(await FinanceDocument.countDocuments({ownerId,'extraction.state':{$in:live}})>=3)fail(409,'読み取り中の書類が完了してから追加してください。');const extraction={state:'queued',hash:doc.hash,jobId:randomUUID(),attempts:0,requestedAt:new Date()};const r=await FinanceDocument.updateOne({_id:doc._id,ownerId,hash:doc.hash,...(doc.extraction?{'extraction.jobId':doc.extraction.jobId}:{extraction:{$exists:false}})},{$set:{extraction}});if(!r.matchedCount)fail(409,'読み取り状況が変わりました。');return documentDetail(ownerId,documentId)}
function workerScope(agent:any){if(!agent.documentEnabled)fail(403,'Document capability required');return {ownerId:agent.ownerId,accountId:{$in:agent.accountIds}}}
export async function claimDocument(agent:any){const scope=workerScope(agent),now=new Date();await FinanceDocument.updateMany({...scope,'extraction.state':'working','extraction.leaseUntil':{$lte:now},'extraction.attempts':{$gte:2}},{$set:{'extraction.state':'failed'},$unset:{'extraction.lease':'','extraction.leaseUntil':''}});const lease=randomUUID(),doc:any=await FinanceDocument.findOneAndUpdate({...scope,$or:[{'extraction.state':'queued'},{'extraction.state':'working','extraction.leaseUntil':{$lte:now},'extraction.attempts':{$lt:2}}]},{$set:{'extraction.state':'working','extraction.lease':lease,'extraction.leaseUntil':new Date(Date.now()+120000),'extraction.agentId':agent._id},$inc:{'extraction.attempts':1}},{new:true,sort:{'extraction.requestedAt':1}}).lean();return {job:doc?{id:String(doc._id),lease,hash:doc.hash,mimeType:doc.mimeType,size:doc.size}:null}}
const jobFilter=(agent:any,documentId:string,lease:any)=>{if(typeof lease!=='string'||lease.length>100)fail(400,'Invalid lease');return {...workerScope(agent),_id:id(documentId),'extraction.state':'working','extraction.agentId':agent._id,'extraction.lease':lease,'extraction.leaseUntil':{$gt:new Date()}}}
export async function workerDocument(agent:any,documentId:string,lease:any){const doc:any=await FinanceDocument.findOne(jobFilter(agent,documentId,lease)).lean();if(!doc||doc.extraction.hash!==doc.hash)fail(409,'読み取り対象が変わりました。');return downloadDocument(String(agent.ownerId),documentId)}
export async function finishDocument(agent:any,documentId:string,body:any){const filter=jobFilter(agent,documentId,body?.lease),doc:any=await FinanceDocument.findOne(filter).lean();if(!doc||doc.hash!==body.hash||doc.extraction.hash!==doc.hash)fail(409,'読み取り対象が変わりました。');let result:any;if(body.failed!==true){try{result=validateDocumentExtraction(body.result)}catch{fail(400,'書類の読み取り根拠を確認できません。')}}const r=await FinanceDocument.updateOne({...filter,hash:doc.hash},{$set:{'extraction.state':result?'ready':'failed',...(result?{'extraction.result':result,'extraction.completedAt':new Date(),'extraction.processor':'claude-vision'}:{})},$unset:{'extraction.lease':'','extraction.leaseUntil':''}});if(!r.matchedCount)fail(409,'読み取りが更新されました。');return {success:true}}
export async function linkDocument(ownerId:string,documentId:string,body:any){const source=await owned(ownerId,documentId);if(source.hash!==body?.hash||body.confirm!==true||!Number.isSafeInteger(body.line))fail(400,'書類と関連付ける明細を確認してください。');const detail=await documentDetail(ownerId,documentId),record=detail.reading.records?.find((r:any)=>r.index===body.record),match=detail.matches.find((m:any)=>m.record===body.record);if(!record||!match?.matches.some((m:any)=>m.line===body.line))fail(409,'この明細への一致根拠がありません。');let draft=await readDraft(ownerId,String(source.importId),body.line);if(draft.locked||draft.revision!==body.revision||draft.key!==body.key||draft.sourceHash!==body.sourceHash)fail(409,'明細が更新されています。');const existing:any=await FinanceDocument.findOne({ownerId,importId:source.importId,line:body.line,hash:source.hash}).lean();if(existing)return {documentId:String(existing._id),alreadyAttached:true};if(!draft.revision)draft=await saveDraft(ownerId,String(source.importId),body.line,{revision:0,key:draft.key,sourceHash:draft.sourceHash,values:draft.values,remember:[],confirm:false});const {bytes}=await downloadDocument(ownerId,documentId),before=new Set(draft.documents.map((d:any)=>d.id));const after=await addDocument(ownerId,String(source.importId),body.line,{revision:draft.revision,key:draft.key,sourceHash:draft.sourceHash,kind:source.kind,name:source.name},bytes,source.mimeType),added=after.documents.find((d:any)=>!before.has(d.id));if(!added)fail(409,'関連付けを再確認してください。');const attached=await FinanceDocument.updateOne({_id:added.id,ownerId,hash:source.hash},{$set:{extraction:{state:'ready',hash:source.hash,jobId:randomUUID(),result:source.extraction.result,completedAt:source.extraction.completedAt,processor:source.extraction.processor},selectedRecord:{index:body.record,confirmedAt:new Date(),sourceDocumentId:documentId}}});if(!attached.matchedCount)fail(409,'添付状態が変更されました。明細を再読込してください。');return {documentId:added.id,alreadyAttached:false}}
